title: Daily.AI
theme: jekyll-theme-chirpy
baseurl: ""
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude: [Gemfile, Gemfile.lock, node_modules, vendor]

# GitHub Pages support
github:
  is_project_page: false
